name: build and test feature branch
on:
    push:
        branches:
            - feature/*
jobs:
    build-feature:
        runs-on: windows-latest
        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v2
        
            - name: Configurar Node.js 18
              uses: actions/setup-node@v3
              with:
                node-version: '18'
        
            - name: Instalar paquetes de Node.js
              run: npm install
        
            - name: Instalar Angular CLI
              run: npm install -g @angular/cli
        
            - name: Ejecutar pruebas
              run: ng test
        
            - name: Compilar aplicación Angular
              run: ng build
                echo "run test and build angular app"